knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        google:
            type: google
            client_id: '%env(OAUT_GOOGLE_ID)%'
            client_secret: '%env(OAUT_GOOGLE_SECRET)%'
            redirect_route: connect_check
            redirect_params: {}
